### ISSUE TITLE
Export PlyrComponent from 'ngx-plyr'

### ISSUE THREAD

**Issue by zerocewl** [smnbbrv/ngx-plyr#1]
Hey,

nice work so far!

I have only a minor issue with using the PlyrComponent.
It only works with 

`import { ɵa as PlyrComponent } from 'ngx-plyr';`

but maybe the original import 

`import { PlyrComponent } from 'ngx-plyr';`

would be nice to use ;-)

Maybe your /node_modules/ngx-plyr/ngx-plyr.d.ts needs an update?

Best regards!

**Comment by smnbbrv** [comment]
thanks for hint! forgot to export the component :)
