### ISSUE TITLE
Loading plyrPoster Multiple Times

### ISSUE THREAD

**Issue by maso2k17** [smnbbrv/ngx-plyr#10]
Sorry me again, not sure if this is a an issue, or my code, but I'm seeing that when I have a plyrPoster specified in the HTML the image is loaded twice when the page loads?

I've had a bit of a hard time working out why, all I can really say at this point is that if I remove the plyPoster the image doesn't load at all (obviously).

`<div plyr style="width: 100%" [plyrPoster]="scene.thumbnail" [plyrSources]="scene.url" (plyrInit)="player = $event" (plyrPlay)="played($event)" ></div>`

I've confirmed that the value its reading is correct, it is just a single URL.

Just wondered if you might have any suggestions how to further diagnose what might be causing it?

**Comment by smnbbrv** [comment]
Hi, 

Is there a way to reproduce this? Do you see this effect in demo as well?

**Comment by smnbbrv** [comment]
closing as long as not being able to reproduce. Please reopen it if you can provide a stackblitz example of the problem
