### ISSUE TITLE
Target already setup when changing player options

### ISSUE THREAD

**Issue by sirajtahra** [smnbbrv/ngx-plyr#12]
###Expected Behaviour
changing options after player initialization  should reinitialize the player without a problem. 
###Current Behaviour 
changing player options outputs: 'Target already setup'

###description
`initPlyr` method destroys the player then creates it, after the destruction the videoElement getter method returns a video element which still contains the plyr instance, however `document.getElementsByTagName('video')[0].plyr` returns undefined at this point.

I wonder if this could be a change detection or NgZone issue

**Comment by sirajtahra** [comment]
the `destroyPlayer()` method does not seem to update the `this.videoElement` properly

**Comment by smnbbrv** [comment]
Hi,

thanks for raising the issue.

I think the primary issue is that the element that is called `original` in the original library is not an original element; it's a clone instead.

See https://github.com/sampotts/plyr/blob/80aa6ffe435b170466838f977d52438a95e22186/src/js/plyr.js#L149

I need to think on a stable and reliable solution for that

**Comment by sirajtahra** [comment]
they clone the original element so it doesn't get lost when you destroy the plyr instance so it seems, I made a pull request that addresses this issue

**Comment by smnbbrv** [comment]
the problem is it **gets** lost, because the clone !== element.

Yep, I saw the PR, the problem there is that it uses undocumented / internal`elements.original`, that's why I can't take it as a long term solution.

However, it helped me a lot localizing the issue, thank you!

**Comment by smnbbrv** [comment]
Please check @1.2.2
