### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by Tatenda** [smnbbrv/ngx-plyr#14]
Is this project mearnt to work with Angular Universal.. When I use it in my app that has SSR it crashed because it cannot identify document (which is expected). Any solutions to this?

**Comment by smnbbrv** [comment]
Hi @Tatenda 

that's a good question.

I'm not using SSR anywhere (yet), so I can't really help with this. In my defence, this library does not use `document`, that part most likely comes from `plyr`

**Comment by smnbbrv** [comment]
If you are able to find out what's the problem and we can fix it, please share / create a PR (the second would be wonderful)

**Comment by Tatenda** [comment]
This is actually an issue with plyr. They don't seem like they are willing to fix that any time soon so it needs someone to create a pull request for it.

**Comment by henaff** [comment]
This is not an issue with plyr, it needs to dynamiccaly import the plyr constructor in ngAfterViewInit

**Comment by ImrozKhan21** [comment]
@henaff Can you tell me how to import the plyr dynamically? I am importing PlyrModule in my modules which is causing the issue, are you saying to not import that PlyrModule?

**Comment by ciriousjoker** [comment]
This seems to be not working at all.
In my case, as soon as I import the `PlyrModule` in the `app.module.ts`, compile and run the Express Server, instead of listening it just spits out javascript code into the terminal.

When I ctrl + c the Node process, I get this 


```log
...
ml"))?"index.original.html":"index.html";return server.set("view engine","html"),server.set("views",distFolder),server.use(compression()),server.get("*.*",express.static(distFolder,{maxAge:"1y"})),server.get("*",(req,res)=>{res.render(indexHtml,{req,providers:[{provide:common.mr,useValue:req.baseUrl}]})}),server}__name(app,"app")})();var __webpack_export_target__=exports;for(var i in __webpack_exports__)__webpack_export_target__[i]=__webpack_exports__[i];__webpack_exports__.__esModule&&Object.defineProperty(__webpack_export_target__,"__esModule",{value:!0})})();










ReferenceError: document is not defined
    at F:\project\dist\frontend\server\de\main.js:3:4430149
    at F:\project\dist\frontend\server\de\main.js:3:4430403
    at F:\project\dist\frontend\server\de\main.js:3:4562913
    at Object.<anonymous> (F:\project\dist\frontend\server\de\main.js:3:4563145)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

The first part seems like it's just the ~9mb of the compiled server bundle as a string, the second part is more interesting since SSR doesn't provide the `document` object.

**Comment by ciriousjoker** [comment]
@smnbbrv Would you be open to PRs regarding this?

**Comment by smnbbrv** [comment]
Hi, yes, of course

**Comment by banezemun83** [comment]
Is there any news regarding this? I have the same issue with document not being defined.

**Comment by ciriousjoker** [comment]
@banezemun83 I tried for a short time, but it seems to be caused by plyr itself. Therefore I'll probably use plyr directly and try to fix that first, but I'm busy with other stuff for the time being, perhaps I'll figure something out in 4 months or so
