### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by bradrice** [smnbbrv/ngx-plyr#19]
How do I implement an audio only player? I don't see any examples, only video player examples.

**Comment by smnbbrv** [comment]
Please look at the demo and it’s source code

**Comment by bradrice** [comment]
I did, but I keep getting UI for video and not audio.

**Comment by smnbbrv** [comment]
Could you post an example at stackblitz?

This is from the demo and it works:

![image](https://user-images.githubusercontent.com/13453858/61615030-605ea300-ac65-11e9-9cd9-61e53987797a.png)

**Comment by bradrice** [comment]
I see it when I go to the demo url. How do I look at the source of that demo? I can't seem to find an implementation of the audio player in this github source tree.

**Comment by smnbbrv** [comment]
Here it is https://github.com/smnbbrv/ngx-plyr/blob/c8516700e377997f55cbeb33a81e7efc83fdd492/src/app/app.component.html#L43

Please note that the current version of ngx-plyr is 3.0.0, please update to the latest one

**Comment by bradrice** [comment]
Thank you, but I'm still getting some weird behavior with regard to the UI.

I'm also getting a javascript error: 
`zone-evergreen.js:172 Uncaught TypeError: Cannot read property 'firstChange' of undefined
    at SafeSubscriber._next (ngx-plyr.js:109)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:185)
    at SafeSubscriber.next (Subscriber.js:124)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at TapSubscriber._next (tap.js:46)
    at TapSubscriber.next (Subscriber.js:49)
    at TakeSubscriber._next (take.js:35)
    at TakeSubscriber.next (Subscriber.js:49)
    at FilterSubscriber._next (filter.js:33)`

![Screen Shot 2019-07-25 at 1 57 55 PM](https://user-images.githubusercontent.com/272352/61897109-58606680-aee4-11e9-8a29-495bca946770.png)

**Comment by smnbbrv** [comment]
Unfortunately there is no possibility to debug the screenshots :)

Could you please create a minimal reproduction on stackblitz?

**Comment by bradrice** [comment]
Here is my effort. I see an error is covering up my app. But under that, I can't figure out how to add styles to the material.

https://stackblitz.com/edit/angular-k5m1hj

**Comment by bradrice** [comment]
Perhaps we can start here. What is that error?

https://stackblitz.com/edit/angular-estcfi

**Comment by smnbbrv** [comment]
The error should be gone after installing 3.0.1.

To add the styles please follow the very first installation step on the README - this is missing in your stackblitz

**Comment by bradrice** [comment]
Great thanks. How do you get Stackblitz to recognize the css?

styleUrls: ["node_modules/plyr/dist/plyr.css"]

It says file not found. I have trouble understanding how stackblitz finds the node_modules files.

**Comment by bradrice** [comment]
I finally figured out my problem. I was trying to add the styles to the component instead of the angular.json.
