### ISSUE TITLE
Add a demo or stackblitz example

### ISSUE THREAD

**Issue by zerocewl** [smnbbrv/ngx-plyr#2]
A demo page or a link to a working stackblitz instance would be nice for every new user.
Simple e.g.:

https://stackblitz.com/edit/ngx-plyr

**Comment by smnbbrv** [comment]
That's a good idea, which definitely needs to be done sooner or later.

The question is what is preferable, the demo app on github pages or stackblitz? The latter one is more complicated to maintain, but is easier to start with.
