### ISSUE TITLE
Adding this attribute is breaking videos loaded from S3

### ISSUE THREAD

**Issue by anaganisk** [smnbbrv/ngx-plyr#20]
https://github.com/smnbbrv/ngx-plyr/blob/412c3b82e8c94c3fac8e395478af13ff6ade5322/projects/ngx-plyr/src/lib/plyr/plyr.component.ts#L190

**Comment by anaganisk** [comment]
this could be possible reason for #8

**Comment by anaganisk** [comment]
as outlined here https://github.com/sampotts/plyr/issues/1255

**Comment by smnbbrv** [comment]
Hi @anaganisk 

that's actually something I don't like looking at. So much that I am even ready for another major version within 2 days.

Please check v3.0.0

**Comment by anaganisk** [comment]
this.videoElement.setAttribute('crossorigin', '');
Feels like the same attribute is part of  v3.0.0 too, it will definitely break s3 videos. And many sourced

**Comment by smnbbrv** [comment]
Did you try it?

**Comment by anaganisk** [comment]
Yes, unless that attribute is removed its breaking.

**Comment by smnbbrv** [comment]
Again, have you tried `npm i ngx-plyr@^3.0.0`? Does it fail? Could you provide an example?

**Comment by smnbbrv** [comment]
Closing as resolved
