### ISSUE TITLE
*ngIf with ngx-plyr

### ISSUE THREAD

**Issue by bradrice** [smnbbrv/ngx-plyr#22]
I stere a way to show and hide the ngx-plyr component based upon some variable? I have an hasAudio boolean that I am using and when I do I get errors when I try to start the audio on plyrCanPlay.

` <div *ngIf="hasAudio"  mat-card-image plyr plyrTitle="Audio" plyrType="audio" [plyrPlaysInline]="true" [plyrCrossOrigin]="false"
          [plyrSources]="audioSources"></div>`

`this.playSub = this.plyr.plyrCanPlay.subscribe((data)=> {
        console.log('Ready to play');
        this.play();
    });
`

ERROR TypeError: Cannot read property 'plyrCanPlay' of undefined

**Comment by smnbbrv** [comment]
Why don’t you just use (plyrCanPlay)=“yourfunc($event)”?

**Comment by bradrice** [comment]
That looks cool. How do I make the player play using that? this.target.play() doesn't work.

**Comment by bradrice** [comment]
(plyrCanPlay)="myfunc($event)" never fires. What do I need to do?
