### ISSUE TITLE
attribution for hls driver?

### ISSUE THREAD

**Issue by gbeane** [smnbbrv/ngx-plyr#29]
Does inclusion of hlsjs-plyr-driver.js in my project constitute a 'substantial portion' and require attribution? My project is not currently public, but in anticipation of it eventually being public I've added the copywrite and license header to my copy of hlsjs-plyr-driver.js.

**Comment by smnbbrv** [comment]
Hi @gbeane 

it's definitely not a substantial part of the software, furthermore it is just a documentation; it's not included in the library as well.

The license text I have in this repo is a standard MIT; it would be totally fine (to me) if you clone the whole repository and reuse / relicense it under any conditions.

**Comment by smnbbrv** [comment]
I hope this answered the question, if not, please feel free to reopen the issue :)
