### ISSUE TITLE
Type definitions for 3.5.7

### ISSUE THREAD

**Issue by bhayward93** [smnbbrv/ngx-plyr#31]
I upgraded my plyr library 3.5.6 > 3.5.7, and am now getting a variety of fun looking issues with type definitions. Are there plans to add these typings for 3.5.7?

![image](https://user-images.githubusercontent.com/18596813/74195501-3eedf480-4c53-11ea-9408-12f8748213ee.png)

**Comment by smnbbrv** [comment]
It would be awesome if the types are not maintained in this lib because, well, it's not its goal :)

Somebody should create a PR at definitelytyped.

**Comment by smnbbrv** [comment]
Please try v4.0.0
