### ISSUE TITLE
PlyrOptions doesn't seem to accept the config

### ISSUE THREAD

**Issue by TimThompson99** [smnbbrv/ngx-plyr#32]
Could be that I'm doing it incorrectly, but the options don't seem to affect the Plyr. Setting the sources working fine.

<plyr style="display: block; width: 100%;" plyrTitle="Video 1" [plyrSources]="videoSources" [plyrOptions]="videoOptions" (plyrInit)="player = $event"
 (plyrPlay)="play($event)" (plyrTimeUpdate)="timeUpdate($event)"></plyr>

    this.videoOptions = [
      {fullscreen: {enabled: false}},
      {controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'captions', 'settings']}
    ];

**Comment by smnbbrv** [comment]
Hi @TimThompson99 

plyrOptions is an object and you pass an array. See https://github.com/sampotts/plyr#options for more info

**Comment by MagneticLlama** [comment]
It would be nice to see an example of how it should be formatted.
