### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by bradrice** [smnbbrv/ngx-plyr#41]
Is there a way to get this to work with IE11 and Angular 9? I notice the demo page doesn't work in IE11 so I'm assuming you haven't worried about getting it working in a legacy Internet Explorer?

**Comment by smnbbrv** [comment]
Hi @bradrice 

Normally it is enough to enable ie-related polyfills in the angular app.

So far the lib does not directly use any CSS nor non-angular code I assumed it would just work in ie as is when the related polyfills get enabled. However this is decision of the app developer, not the lib. 

If you want to test it with ie just clone the repo locally and enable missing polyfills in src/polyfills.ts

**Comment by bradrice** [comment]
The issue I get is in IE11:

Object doesn't support property or method 'find'
scripts.js (552,5)

which when I run the debugger is plyr.js

**Comment by smnbbrv** [comment]
that means that looks like you would need a polyfill for Array.prototype.find...
