### ISSUE TITLE
Can we make seek buttons to center with default options?

### ISSUE THREAD

**Issue by askynet** [smnbbrv/ngx-plyr#44]
![Screenshot 2020-05-20 at 11 55 09 PM](https://user-images.githubusercontent.com/38763681/82483624-4cd6cf80-9af6-11ea-949a-941a0cfad4a5.png)

**Comment by smnbbrv** [comment]
Hi,

all questions related to customizing plyr could be addressed at https://github.com/sampotts/plyr
