### ISSUE TITLE
Dynamicly change src and provider from yoututbe and vimeo

### ISSUE THREAD

**Issue by Smoodys** [smnbbrv/ngx-plyr#5]
I'm trying to know how can i change dynamically my src and provider, so this (code below) works at the beginning with default value in variables, but when i tried to change them the player goes black.
```
  videoid: string = 'bTqVqk7FSmY';
  videoprovider: string = 'youtube';

videoSources: Plyr.Source[] = [
    {
      src: this.videoid,
      provider: this.videoprovider,
    },
  ];
```

If anyone change can help me with that thanks!

**Comment by Alsmith141510** [comment]
I do this all the time. I have a drop down with the YouTube vide  id. OnChange event I change the source of the player by calling the changVideoSource function below.

Hope this helps.
changeVideoSource (**_videoSource_** :string)
{
 this.player.source ={
 type: Video,
Sources: [
{   src: **_videosource_**,
   provider: 'youtube',
},
]
}
}

**Comment by smnbbrv** [comment]
Thanks @Alsmith141510 

That's right: you need to recreate the object that the change detection understands that something got changed
