### ISSUE TITLE
'plyr' is not a known element

### ISSUE THREAD

**Issue by dineshadhikari** [smnbbrv/ngx-plyr#6]
_<plyr style="width: 640px;" plyrTitle="Video 1" [plyrSources]="videoSources" (plyrInit)="player = $event" (plyrPlay)="played($event)"></plyr>_

However - using it as an inline component doesn't seem to be working properly:

**Comment by smnbbrv** [comment]
Hi, are you sure you added plyr module into your module?

**Comment by smnbbrv** [comment]
Closing as inactive / needs more info
