### ISSUE TITLE
Typings Issue

### ISSUE THREAD

**Issue by MichaelCastelbuono** [smnbbrv/ngx-plyr#7]
Hi I'm in an angular 7.2.2 environment and I'm getting the following errors when importing the `ngx-plyr` module. And probably more importantly I'm using typescript 3.2.4.

```
ERROR in node_modules/ngx-plyr/lib/plyr-driver/plyr-driver.d.ts(3,19): error TS2694: Namespace '"plyr"' has no exported member 'Options'.
node_modules/ngx-plyr/lib/plyr-driver/plyr-driver.d.ts(7,11): error TS2709: Cannot use namespace 'Plyr' as a type.
node_modules/ngx-plyr/lib/plyr-driver/plyr-driver.d.ts(8,18): error TS2694: Namespace '"plyr"' has no exported member 'SourceInfo'.
node_modules/ngx-plyr/lib/plyr-driver/plyr-driver.d.ts(12,11): error TS2709: Cannot use namespace 'Plyr' as a type.
node_modules/ngx-plyr/lib/plyr-driver/plyr-driver.d.ts(15,45): error TS2709: Cannot use namespace 'Plyr' as a type.
node_modules/ngx-plyr/lib/plyr/plyr.component.d.ts(14,22): error TS2709: Cannot use namespace 'Plyr' as a type.
```

**Note** Prior to this I was getting an error that types for `plyr` could not be found:
```
 Could not find a declaration file for module 'plyr'.
```
So I added a new declarations.d.ts file and added `declare module 'plyr';`.

**Comment by smnbbrv** [comment]
Hi, 

This is an issue of original plyr. The typings are just not there and there is a corresponding issue  https://github.com/sampotts/plyr/issues/296 and there are rumors the whole repo will be migrated to typescript and the problem will be solved sooner or later 

In this repo I use synthetic typings, see the repo code. If you want to use it as well, you just need to copy those typings and properly configure your tsconfig.

**Comment by MichaelCastelbuono** [comment]
Thanks for the reply. I did notice that the original `plyr` had no typings (which was the original error I got), so usually that's just solved by making your own `declarations.d.ts` file and adding `declare module 'plyr'`. However, that's when I got the above errors about `ngx-plyr`, for some reason I think typescript is picking up some of your `.d.ts` files, but not all of them.

I'll try and manually add them all to my local `typings` folder and see if that fixes it.

**Comment by MichaelCastelbuono** [comment]
Are you using this [file](https://gist.githubusercontent.com/wagich/e9a4e7cade3e8e9363e718ae62299371/raw/0e9946af91c686536c0f80bcd8246f022cbfdc78/plyr.d.ts) in your repository to get the declarations for `plyr`? I see a couple of references to `import Plyr from 'plyr';` in your `.d.ts` files, such as in `plyr-driver.d.ts` and that seems to be causing the issues for me.

**Comment by smnbbrv** [comment]
Exactly this file is used inside the repo, right. It is taken from the issue I linked above. I slightly adapted it but 99% is the same.

Then, probably, you could try to use the file from the repo as `.d.ts`...

**Comment by MichaelCastelbuono** [comment]
Oh my turns out I just had to use yours https://github.com/smnbbrv/ngx-plyr/blob/master/typings/plyr/index.d.ts :) For some reason, I didn't notice you had that there in your repo. After using that as the declaration in my file it goes away. Maybe you should mark that as a requirement in your README.md? Thanks!

**Comment by smnbbrv** [comment]
Super! I will add it definitely.

Could you please share your tsconfig that I can give it as example?

**Comment by MichaelCastelbuono** [comment]
I'm actually not referencing it directly in my tsconfig, it somehow picks it up on its own.
```
{
	"compileOnSave": false,
	"compilerOptions": {
		"baseUrl": "./",
		"paths": {
			"@app/*": ["src/app/*"],
			"@env/*": ["src/environments/*"]
		},
		"outDir": "./dist/out-tsc",
		"sourceMap": true,
		"declaration": false,
		"moduleResolution": "node",
		"emitDecoratorMetadata": true,
		"strict": true,
		"experimentalDecorators": true,
		"target": "es5",
		"typeRoots": ["node_modules/@types"],
		"lib": ["es2017", "dom"],
		"noUnusedLocals": true,
		"strictPropertyInitialization": false
	}
}
```
I put the file within `src/types/plyr/index.d.ts` but I think it would work in any `.d.ts`. Again I'm using typescript 3.2.4.
